/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package training.gradle;

import com.google.gson.Gson;
import training.gradle.model.Product;
import training.gradle.util.StringUtil;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Belajar Gradle");

        Gson gson = new Gson();

        Product p1 = new Product("1", "handphone politron");
        System.out.println(StringUtil.INSTANCE.toUpper(p1.getName()));
    }
}
